### ISSUE TITLE
Hacktoberfest updates

### ISSUE THREAD

**Issue by Aman-zishan** [nandan-unni/Hello-World#7]
https://hacktoberfest.digitalocean.com/hacktoberfest-update?s=08

please  do update the repo by adding the tag "hacktoberfest" and labelling PRs as "hacktoberfest-accepted" according to the new update inorder to make a repository hacktoberfest valid.

Thanks in advance!

**Comment by Nandan-unni-zz** [comment]
Done, and thanks for the reminder :)
